branches:
  - master
pulls: false
projects:
  ServerTools:
    path: ""
    icon: resources/servertools_logo.png
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^2.1.0
      - src: JackMD/ConfigUpdater/ConfigUpdater
        version: ^1.0.0
      - src: matcracker/FormLib/FormLib
        version: ^1.2.0
...
