---
name: ServerTools
main: matcracker\ServerTools\Main
version: 0.4.1
api: 4.0.0

load: POSTWORLD
author: matcracker
description: "ServerTools is a set of tools that allows you to manage your server directly from the game!"
website: https://github.com/matcracker/ServerTools
permissions:
  st.command.servertools:
    description: "Allows the user to run the command /servertools"
    default: op
  st.ui.file-explorer:
    description: "Allows to use the file explorer function"
    default: op
    children:
      st.ui.file-explorer.write:
        description: "Give the permission to create/edit files and folders."
        default: false
  st.ui.clone:
    description: "Allows to use the cloning function"
    default: false
  st.ui.plugin-manager:
    description: "Allows to use the plugin manager function"
    default: false
  st.ui.poggit-downloader:
    description: "Allows to use the poggit plugin downloader function"
    default: false
  st.ui.restart:
    description: "Allows to use the restart function"
    default: op
...
